services:
  markitdown-endpoint:
    build: .
    restart: unless-stopped
    environment:
      API_KEY: ${API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    # If you want to persist data, uncomment and adjust the following:
    # volumes:
    #   - ./data:/app/data 